name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: npm ci
        run: npm ci


      - name: npm test
        run: npm test
        env:
          CI: true

      - name: npm shrinkwrap
        run: npm shrinkwrap

      - run: npm run build

      - name: npm auth & publish
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
